### PR TITLE
Hints

### PR DESCRIPTION
**Pull request by helin24**
@lpercival added your notes for hints - do you want to add examples for some of the python/JS hints?

### CODE REVIEW

**Comment by lpercival** [comment]
So, I wasn't planning on giving examples for hints. In my mind hints were like suggestions to help them figure out what to Google, where if I go into giving examples it's more like actually telling them how to do it and at that point they can look at the solutions

**Comment by lpercival** [comment]
On second thought, I can see the value of an example for at least the Python indentation item. I'll try to update later today

**Comment by helin24** [comment]
Ah I see, okay. I'm fine with that. I'll make some edits and merge this tomorrow!

**Comment by helin24** [comment]
Oh haha I wrote my message before I saw yours. Okay, I'll merge this for now and you can decide whether to add or revert the note I left.

**Pull request merged**
